export const FETCH_CURRENT_PRICES_REQUEST = "FETCH_CURRENT_PRICES_REQUEST";
export const FETCH_CURRENT_PRICES_SUCCESS = "FETCH_CURRENT_PRICES_SUCCESS";
export const FETCH_CURRENT_PRICES_ERROR = "FETCH_CURRENT_PRICES_ERROR";